-- MySQL Script generated by MySQL Workbench
-- Sun Mar  5 20:42:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`REPORT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`REPORT` (
  `idREPORT` INT NOT NULL AUTO_INCREMENT,
  `clients_per_month` INT NULL,
  `occupied_per_month` INT NULL,
  `free_per_month` INT NULL,
  PRIMARY KEY (`idREPORT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ROOM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ROOM` (
  `idROOM` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `capacity` INT NULL,
  `price` INT NULL,
  `REPORT_idREPORT` INT NOT NULL,
  PRIMARY KEY (`idROOM`, `REPORT_idREPORT`),
  INDEX `fk_ROOM_REPORT1_idx` (`REPORT_idREPORT` ASC) VISIBLE,
  CONSTRAINT `fk_ROOM_REPORT1`
    FOREIGN KEY (`REPORT_idREPORT`)
    REFERENCES `mydb`.`REPORT` (`idREPORT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENT` (
  `idCLIENT` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `date_of_birth` DATE NULL,
  `arrival_date` DATE NULL,
  `departure_date` DATE NULL,
  `length_of_stay` INT NULL,
  `ROOM_idROOM` INT NOT NULL,
  INDEX `fk_CLIENT_ROOM1_idx` (`ROOM_idROOM` ASC) VISIBLE,
  PRIMARY KEY (`idCLIENT`, `ROOM_idROOM`),
  CONSTRAINT `fk_CLIENT_ROOM1`
    FOREIGN KEY (`ROOM_idROOM`)
    REFERENCES `mydb`.`ROOM` (`idROOM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WORKER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`WORKER` (
  `idWORKER` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `date_of_birth` DATE NULL,
  `position` VARCHAR(45) NULL,
  `experience` INT NULL,
  PRIMARY KEY (`idWORKER`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
